<?php

/**
 * Default configuration values. Some of the settings here are for backwards compatibility.
 *
 * Please do not edit this file. Edit config.php instead.
 * (If it doesn't exist yet, make a copy of config.example.php and edit that.)
 */

$default_sql_settings = array(
	// MySQL connection options.
	'host' => 'localhost',
	'user' => '',
	'pass' => '',
	'name' => '',
	// Table prefix: use this to run multiple installations on the same database.
	'prefix' => 'jul_', // FIXME: this isn't used yet.

	// Character encoding settings should probably not be altered.
	// If you are working with legacy data, you might potentially run into problems.
	// To convert your tables: alter table `table_name` convert to character set utf8mb4 collate utf8mb4_bin
	'connection' => 'utf8mb4', // FIXME: this isn't used yet.
	'db_collation' => 'utf8mb4',
	't_charset' => 'utf8mb4',
	't_collation' => 'utf8mb4_bin',
);

$default_forum_settings = array(
	// Board settings.
	'board_name' => 'Board Name',
	'board_title' => 'Board Title',
	'site_url' => 'http://example.com',
	'site_name' => 'Site Name',

	// Default date/time formatting. See PHP's date() function for help.
	// <http://php.net/manual/en/function.date.php>
	'date_format_long' => 'm-d-y h:i:s A',
	'date_format_short' => 'm-d-y',

	// Various hardcoded settings, most of them just legacy.
	'irc_enable_notifications' => false, // Toggles the IRC bot callback code. See xk_ircsend() in lib/function.php.
	'irc_header_title' => 'IRC Chat - BadnikZONE, #tcrf, #x',
	'irc_channels' => '#tcrf,#x',
	'irc_servers' => array('irc.badnik.zone', 'irc.rustedlogic.net', 'irc.tcrf.net'),

	// Ikachan! :D!
	'display_ikachan' => false,
	// Settings of the top menu. This is an array of routes: use only specified routes in lib/routing.php.
	// Custom routes can be set as well. The wiki is an example here.
	'top_menu_items' => array(
		array(
			array('@home', 'Main'),
			array('@memberlist', 'Memberlist'),
			array('@activeusers', 'Active users'),
			array('@calendar', 'Calendar'),
			array('http://tcrf.net', 'Wiki'),
			array('@irc', 'IRC Chat'),
			array('@online', 'Online users'),
		),
		array(
			array('@ranks', 'Ranks'),
			array('@faq', 'Rules/FAQ'),
			array('@stats', 'Stats'),
			array('@latestposts', 'Latest Posts'),
			array('@hex', 'Color Chart'),
			array('@smilies', 'Smilies'),
		),
	),
);
