<?php
  $GLOBALS['jul_settings']['board_title']='<img src="images/mariomovie/thedata.png">';
  $newthreadpic='<img class="post" src="images/mariomovie/newthread.png" alt="New thread" title="New thread">';
  $newreplypic='<img class="post" src="images/mariomovie/newreply.png" alt="New reply" title="New reply">';
  $newpollpic='<img class="post" src="images/mariomovie/newpoll.png" alt="New poll" title="New poll">';
  $threadclosedpic='<img class="post" src="images/mariomovie/threadclosed.png" alt="Thread closed" title="Thread closed">';
  $bgimage='images/mariomovie/zeroesbg3.png';
  $bgcolor='101010';
  $font='\'Courier New\', monospace';
  $font2='Tahoma, sans-serif';
  $textcolor='cccccc';
  $linkcolor='eeeeee';
  $linkcolor2='ffffff';
  $linkcolor3='eeeeee';
  $linkcolor4='ffffff;}
	img.post{ border: none ';
  $malecolor='90a0c0';
  $femalecolor='c090b0';
  $bannedcolor='999999';
  $tablebg1='101010';
  $tablebg2='202020';
  $categorybg='404040';
  $tableheadtext='dddddd';
  $tableheadbg='606060';
  $tableborder='808080';
  $formcss='1';
  $inputborder='707070';
  $scr3='400044';
  $scr7='000000';
  $scr6='DDCCEE';
  $scr2='701077';
  $scr1='A040AA';
  $scr4='701077';
  $scr5='A040AA';

  	$statusicons['new']			= '<img src=images/status-classic/new.gif>';
	$statusicons['newhot']		= '<img src=images/status-classic/hotnew.gif>';
	$statusicons['newoff']		= '<img src=images/status-classic/off.gif>';
	$statusicons['newhotoff']	= '<img src=images/status-classic/hotoff.gif>';
	$statusicons['hot']			= '<img src=images/status-classic/hot.gif>';
	$statusicons['hotoff']		= '<img src=images/status-classic/hotoff.gif>';
	$statusicons['off']			= '<img src=images/status-classic/off.gif>';
